env: dev11111
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rbjf_DEV123
    url: jdbc:mysql://47.104.94.106:3307/SpringCloud?characterEncoding=utf-8&useSSL=false
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnReturn: false
  jpa:
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
server:
  port: 8082
