spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: web
    password: 12345678
    url: jdbc:mysql://101.132.36.144:3306/SpringCloud?characterEncoding=utf-8&useSSL=false
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnReturn: false
  jpa:
    show-sql: true
  redis:
    host: 127.0.0.2
    port: 6379
